# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Initialiser template used to bring up the install ServiceCatalog-Puppet
  {"version": "latest", "framework": "servicecatalog-puppet", "role": "initialiser"}

Parameters:
  EnabledRegions:
    Type: String
    Description: |
      Space or comma seperated list of AWS Regions for which your puppet should operate in
  ShouldCollectCloudformationEvents:
    Type: String
    AllowedValues:
      - True
      - False
    Default: False
  ShouldForwardEventsToEventbridge:
    Type: String
    AllowedValues:
      - True
      - False
    Default: False
  ShouldForwardFailuresToOpscenter:
    Type: String
    AllowedValues:
      - True
      - False
    Default: True
  OrgIAMRoleArn:
    Type: String
    Default: "None"

Conditions:
  NotUsingOrgs: !Equals [!Ref OrgIAMRoleArn, "None" ]
  UsingOrgs: !Not [Condition: NotUsingOrgs]

Resources:
  InitialiserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetInitialiser
      Path: /servicecatalog-product-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  InitialiserProject:
    Type: AWS::CodeBuild::Project
    Condition: NotUsingOrgs
    Properties:
      Name: servicecatalog-product-puppet-initialiser
      Description: "Initialiser for the framework"
      ServiceRole: !GetAtt InitialiserRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
        EnvironmentVariables:
          - Name: ENABLED_REGIONS
            Type: PLAINTEXT
            Value: !Join [ ',', !Split [ ', ', !Ref EnabledRegions]]

          - Name: SHOULD_COLLECT_CLOUDFORMATION_EVENTS
            Type: PLAINTEXT
            Value: !Ref ShouldCollectCloudformationEvents

          - Name: SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE
            Type: PLAINTEXT
            Value: !Ref ShouldForwardEventsToEventbridge

          - Name: SHOULD_FORWARD_FAILURES_TO_OPSCENTER
            Type: PLAINTEXT
            Value: !Ref ShouldForwardFailuresToOpscenter

          - Name: PUPPET_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId

      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - pip install aws-service-catalog-puppet --upgrade
                - servicecatalog-puppet --info set-regions ${ENABLED_REGIONS}
                - servicecatalog-puppet set-config-value should_collect_cloudformation_events ${SHOULD_COLLECT_CLOUDFORMATION_EVENTS}
                - servicecatalog-puppet set-config-value should_forward_events_to_eventbridge ${SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE}
                - servicecatalog-puppet set-config-value should_forward_failures_to_opscenter ${SHOULD_FORWARD_FAILURES_TO_OPSCENTER}
                - servicecatalog-puppet bootstrap-spoke ${PUPPET_ACCOUNT_ID}
            build:
              commands:
                - servicecatalog-puppet --info bootstrap

      TimeoutInMinutes: 60

  InitialiserProjectForOrgs:
    Type: AWS::CodeBuild::Project
    Condition: UsingOrgs
    Properties:
      Name: servicecatalog-product-puppet-initialiser-for-orgs
      Description: "Initialiser for the framework"
      ServiceRole: !GetAtt InitialiserRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
        EnvironmentVariables:
          - Name: ENABLED_REGIONS
            Type: PLAINTEXT
            Value: !Join [ ',', !Split [ ', ', !Ref EnabledRegions]]

          - Name: SHOULD_COLLECT_CLOUDFORMATION_EVENTS
            Type: PLAINTEXT
            Value: !Ref ShouldCollectCloudformationEvents

          - Name: SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE
            Type: PLAINTEXT
            Value: !Ref ShouldForwardEventsToEventbridge

          - Name: SHOULD_FORWARD_FAILURES_TO_OPSCENTER
            Type: PLAINTEXT
            Value: !Ref ShouldForwardFailuresToOpscenter

          - Name: PUPPET_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId

          - Name: ORG_IAM_ROLE_ARN
            Type: PLAINTEXT
            Value: !Ref OrgIAMRoleArn

      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - pip install aws-service-catalog-puppet --upgrade
                - servicecatalog-puppet --info set-regions ${ENABLED_REGIONS}
                - servicecatalog-puppet set-config-value should_collect_cloudformation_events ${SHOULD_COLLECT_CLOUDFORMATION_EVENTS}
                - servicecatalog-puppet set-config-value should_forward_events_to_eventbridge ${SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE}
                - servicecatalog-puppet set-config-value should_forward_failures_to_opscenter ${SHOULD_FORWARD_FAILURES_TO_OPSCENTER}
                - servicecatalog-puppet set-org-iam-role-arn ${ORG_IAM_ROLE_ARN}
                - servicecatalog-puppet bootstrap-spoke ${PUPPET_ACCOUNT_ID}
            build:
              commands:
                - servicecatalog-puppet --info bootstrap

      TimeoutInMinutes: 60

Outputs:
  ServiceCatalogPuppetRepoConsoleURL:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/codesuite/codecommit/repositories/ServiceCatalogPuppet/browse"
  ServiceCatalogPuppetRepoCloneURLSSH:
    Value: !Sub "ssh://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/ServiceCatalogPuppet"
  ServiceCatalogPuppetRepoCloneURLHTTPS:
    Value: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/ServiceCatalogPuppet"
